from __future__ import annotations

import argparse


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="osint-workbench",
        description="Evidence-first passive OSINT workbench. No unrestricted shell or intrusive collection.",
    )
    parser.add_argument("--root", default="data/osint-workbench", help="Workbench data root")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("demo", help="Run a fully synthetic end-to-end demo")
    p.add_argument("--force", action="store_true")

    p = sub.add_parser("init-case", help="Create case, preserve seed and generate five-stream plan")
    p.add_argument("--title", required=True)
    p.add_argument("--seed-type", required=True, choices=["PERSON", "ORGANIZATION", "ADDRESS", "DOMAIN", "ACCOUNT", "ASSET", "DOCUMENT"])
    p.add_argument("--seed", required=True)
    p.add_argument("--aliases", default="")
    p.add_argument("--purpose", required=True)
    p.add_argument("--legal-basis", required=True)
    p.add_argument("--owner-role", default="Главный аналитик")
    p.add_argument("--case-type", default="CORPORATE_DUE_DILIGENCE")
    p.add_argument("--access-class", default="PUBLIC")
    p.add_argument("--jurisdictions", default="UNSPECIFIED")
    p.add_argument("--objective")
    p.add_argument("--approve-plan", action="store_true")
    p.add_argument("--reviewer-id")
    p.add_argument("--synthetic", action="store_true")
    p.add_argument("--case-id")

    p = sub.add_parser("plan", help="Generate a five-stream plan for an existing seed entity")
    p.add_argument("case_id")
    p.add_argument("seed_entity_id")
    p.add_argument("--objective", required=True)
    p.add_argument("--mode", default="IDENTIFY", choices=["IDENTIFY", "INVESTIGATE", "MONITOR"])
    p.add_argument("--approve", action="store_true")
    p.add_argument("--reviewer-id")

    p = sub.add_parser("add-source", help="Register source metadata")
    p.add_argument("case_id")
    p.add_argument("--url", required=True)
    p.add_argument("--title", required=True)
    p.add_argument("--publisher", required=True)
    p.add_argument("--source-type", default="WEB_PAGE")
    p.add_argument("--primary-level", default="UNKNOWN")
    p.add_argument("--jurisdiction", default="UNSPECIFIED")
    p.add_argument("--language", default="und")
    p.add_argument("--reliability-grade", default="D_LEAD")
    p.add_argument("--supports", default="The source was registered.")
    p.add_argument("--does-not-support", default="Any conclusion not separately captured and reviewed.")
    p.add_argument("--access-class", default="PUBLIC")
    p.add_argument("--legal-basis", required=True)
    p.add_argument("--republication-status", default="METADATA_ONLY")

    p = sub.add_parser("capture-file", help="Preserve a local source file with SHA-256")
    p.add_argument("case_id")
    p.add_argument("source_id")
    p.add_argument("path")
    p.add_argument("--access-class")
    p.add_argument("--legal-basis", default="Captured within approved case scope.")

    p = sub.add_parser("capture-text", help="Preserve UTF-8 text from --text or stdin")
    p.add_argument("case_id")
    p.add_argument("source_id")
    p.add_argument("--text")
    p.add_argument("--filename", default="capture.txt")
    p.add_argument("--access-class")
    p.add_argument("--legal-basis", default="Captured within approved case scope.")

    p = sub.add_parser("extract", help="Extract machine-checkable public identifiers from a capture")
    p.add_argument("case_id")
    p.add_argument("source_id")
    p.add_argument("capture_id")
    p.add_argument("--query-plan-id")
    p.add_argument("--job-id")

    p = sub.add_parser("add-entity", help="Create a sourced entity candidate or reviewed entity")
    p.add_argument("case_id")
    p.add_argument("--entity-type", required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--sources", required=True, help="Comma-separated SRC IDs")
    p.add_argument("--aliases", default="")
    p.add_argument("--identifier", action="append", default=[], help="TYPE=VALUE; repeatable")
    p.add_argument("--access-class", default="PUBLIC")
    p.add_argument("--status", default="CANDIDATE")

    p = sub.add_parser("add-claim", help="Record a source claim, not a fact")
    p.add_argument("case_id")
    p.add_argument("--sources", required=True)
    p.add_argument("--statement", required=True)
    p.add_argument("--locator", required=True)
    p.add_argument("--subjects", required=True)
    p.add_argument("--representation", default="STRUCTURED_EXTRACTION")
    p.add_argument("--predicate")
    p.add_argument("--objects", default="")
    p.add_argument("--object-text")
    p.add_argument("--access-class", default="PUBLIC")

    p = sub.add_parser("add-relation", help="Create an evidence-linked relation")
    p.add_argument("case_id")
    p.add_argument("from_entity_id")
    p.add_argument("relation_type")
    p.add_argument("to_entity_id")
    p.add_argument("--sources", required=True)
    p.add_argument("--claims", required=True)
    p.add_argument("--evidence-grade", default="D_LEAD")
    p.add_argument("--status", default="CANDIDATE")

    p = sub.add_parser("approve-finding", help="Create a human-approved finding")
    p.add_argument("case_id")
    p.add_argument("--classification", required=True)
    p.add_argument("--statement", required=True)
    p.add_argument("--evidence-grade", required=True)
    p.add_argument("--sources", required=True)
    p.add_argument("--claims", required=True)
    p.add_argument("--entities", required=True)
    p.add_argument("--reasoning", required=True)
    p.add_argument("--limitations", required=True)
    p.add_argument("--approved-by-role", required=True)
    p.add_argument("--red-team-status", default="PENDING")
    p.add_argument("--alternatives", default="")
    p.add_argument("--access-class", default="PUBLIC")

    p = sub.add_parser("add-gap", help="Record an unresolved research question")
    p.add_argument("case_id")
    p.add_argument("--subjects", required=True)
    p.add_argument("--stream", required=True)
    p.add_argument("--question", required=True)
    p.add_argument("--why", required=True)
    p.add_argument("--evidence-needed", required=True)
    p.add_argument("--owner-role", default="Составной аналитик")
    p.add_argument("--priority", default="P1")
    p.add_argument("--state", default="NOT_CHECKED")
    p.add_argument("--report-effect", default="LIMITS_REPORT")

    p = sub.add_parser("resolve", help="Compare two entities without automatic merge")
    p.add_argument("case_id")
    p.add_argument("entity_a_id")
    p.add_argument("entity_b_id")
    p.add_argument("--query-plan-id")

    p = sub.add_parser("fetch-url", help="Run a single policy-governed passive public HTTP GET")
    p.add_argument("case_id")
    p.add_argument("query_plan_id")
    p.add_argument("pivot_id")
    p.add_argument("url")
    p.add_argument("--title")
    p.add_argument("--publisher", default="Unknown")
    p.add_argument("--source-type", default="WEB_PAGE")
    p.add_argument("--primary-level", default="UNKNOWN")
    p.add_argument("--jurisdiction", default="UNSPECIFIED")
    p.add_argument("--language", default="und")
    p.add_argument("--reliability-grade", default="D_LEAD")
    p.add_argument("--legal-basis", required=True)
    p.add_argument("--republication-status", default="METADATA_ONLY")
    p.add_argument("--max-bytes", type=int, default=10 * 1024 * 1024)
    p.add_argument("--timeout", type=int, default=20)
    p.add_argument("--no-extract", action="store_true")

    p = sub.add_parser("coverage", help="Assess decomposed evidence coverage")
    p.add_argument("case_id")
    p.add_argument("finding_id")

    p = sub.add_parser("graph", help="Build a derived non-authoritative graph view")
    p.add_argument("case_id")
    p.add_argument("--seed-refs", default="")
    p.add_argument("--mode", default="GRAPH")
    p.add_argument("--purpose", default="Evidence-linked case graph")
    p.add_argument("--bounded-hops", type=int, default=2)

    p = sub.add_parser("analyze", help="Run governed independent analysis opinions")
    p.add_argument("case_id")
    p.add_argument("--task", required=True)
    p.add_argument("--input-refs", required=True)
    p.add_argument("--analyzers", default="builtin-evidence-lineage,builtin-graph-contrarian")

    p = sub.add_parser("analyzers", help="List registered built-in analyzers")
    p.add_argument("case_id", nargs="?")

    p = sub.add_parser("report", help="Generate formal evidence-linked Markdown report")
    p.add_argument("case_id")
    p.add_argument("--public", action="store_true")
    p.add_argument("--unredacted", action="store_true")
    p.add_argument("--name", default="main_official_report.md")

    p = sub.add_parser("monitor", help="Create a case change snapshot")
    p.add_argument("case_id")
    p.add_argument("--label", default="manual")

    p = sub.add_parser("summary", help="Show case production state")
    p.add_argument("case_id")

    p = sub.add_parser("verify-journal", help="Verify sequence and SHA-256 chain")
    p.add_argument("case_id")

    p = sub.add_parser("serve", help="Run loopback-only read-only API")
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--expose-local-paths", action="store_true")
    return parser
