from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from father_osint.artifact_identity import MarkerValidatingFetcher
from father_osint.knowledge_factory_store import KnowledgeFactoryStore
from father_osint.pdn_batch import PdnOfficialBatchRunner, load_registry


DEFAULT_REGISTRY = REPO_ROOT / "config" / "pdn_official_documents.json"
DEFAULT_ROOT = REPO_ROOT / "data" / "knowledge_factory" / "pdn_official_batch"
DEFAULT_EXPORT = REPO_ROOT / "reports" / "pdn_live"


def build_marker_map(registry: dict) -> dict[str, tuple[str, ...]]:
    marker_map: dict[str, tuple[str, ...]] = {}
    for item in registry["documents"]:
        if not item.get("enabled", False):
            continue
        url = item.get("source_url")
        markers = tuple(item.get("required_text_markers", []))
        if not url:
            raise ValueError(f"enabled document {item['document_id']} has no source_url")
        if not markers:
            raise ValueError(f"enabled document {item['document_id']} has no required_text_markers")
        marker_map[url] = markers
    return marker_map


def export_sanitized_review(store: KnowledgeFactoryStore, result, export_dir: Path) -> dict[str, str]:
    export_dir.mkdir(parents=True, exist_ok=True)

    source_md = store.root / result.review_md_path
    target_md = export_dir / "REVIEW.md"
    shutil.copyfile(source_md, target_md)

    jsonl_path = export_dir / "batch_review_manifest.jsonl"
    with jsonl_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            json.dumps(
                {
                    "record_type": "BATCH_SUMMARY",
                    "registry_id": result.registry_id,
                    "counters": result.counters,
                    "semantic_extraction_performed": False,
                    "review_required_before_d6": True,
                },
                ensure_ascii=False,
                sort_keys=True,
            )
            + "\n"
        )
        for item in result.results:
            payload = item.to_dict()
            payload["record_type"] = "DOCUMENT_RESULT"
            handle.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")

    readme_path = export_dir / "README.md"
    readme_path.write_text(
        "# PDn live batch review export\n\n"
        "Generated by `scripts/run_pdn_official_batch.py`.\n\n"
        "This directory intentionally contains only sanitized review metadata: public source URLs, "
        "document identifiers, states, hashes, sizes, MIME types, D5 counters and failure reasons. "
        "Exact downloaded originals and extracted document text remain under ignored `data/knowledge_factory/` "
        "and must not be committed to the public repository.\n\n"
        "Files for review:\n"
        "- `REVIEW.md` — human-readable status table;\n"
        "- `batch_review_manifest.jsonl` — machine-readable review records.\n",
        encoding="utf-8",
        newline="\n",
    )

    return {
        "review_md": target_md.relative_to(REPO_ROOT).as_posix(),
        "review_jsonl": jsonl_path.relative_to(REPO_ROOT).as_posix(),
        "readme": readme_path.relative_to(REPO_ROOT).as_posix(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Download approved official PDn documents by registry and prepare D0-D5 review package"
    )
    parser.add_argument("--registry", default=str(DEFAULT_REGISTRY))
    parser.add_argument("--root", default=str(DEFAULT_ROOT))
    parser.add_argument("--export-review", default=str(DEFAULT_EXPORT))
    parser.add_argument("--max-chunk-chars", type=int, default=2400)
    args = parser.parse_args()

    registry = load_registry(args.registry)
    marker_map = build_marker_map(registry)
    store = KnowledgeFactoryStore(args.root)
    result = PdnOfficialBatchRunner(
        store,
        fetcher=MarkerValidatingFetcher(marker_map),
        max_chunk_chars=args.max_chunk_chars,
    ).run(registry)
    exported = export_sanitized_review(store, result, Path(args.export_review))

    payload = {
        "registry_id": result.registry_id,
        "counters": result.counters,
        "local_review_json": result.review_json_path,
        "local_review_md": result.review_md_path,
        "sanitized_export": exported,
        "store_root": str(store.root),
        "documents": [item.to_dict() for item in result.results],
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))

    hard_failures = (
        result.counters["acquisition_failed"]
        + result.counters["acquisition_blocked"]
        + result.counters["compile_failed"]
    )
    return 2 if hard_failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
